/**
 * @fileoverview gRPC-Web generated client stub for recipes
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.0
// source: recipe.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as recipe_pb from './recipe_pb'; // proto import: "recipe.proto"


export class RecipeServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetRecipe = new grpcWeb.MethodDescriptor(
    '/recipes.RecipeService/GetRecipe',
    grpcWeb.MethodType.UNARY,
    recipe_pb.GetRecipeRequest,
    recipe_pb.GetRecipeResponse,
    (request: recipe_pb.GetRecipeRequest) => {
      return request.serializeBinary();
    },
    recipe_pb.GetRecipeResponse.deserializeBinary
  );

  getRecipe(
    request: recipe_pb.GetRecipeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recipe_pb.GetRecipeResponse>;

  getRecipe(
    request: recipe_pb.GetRecipeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recipe_pb.GetRecipeResponse) => void): grpcWeb.ClientReadableStream<recipe_pb.GetRecipeResponse>;

  getRecipe(
    request: recipe_pb.GetRecipeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recipe_pb.GetRecipeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/recipes.RecipeService/GetRecipe',
        request,
        metadata || {},
        this.methodDescriptorGetRecipe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/recipes.RecipeService/GetRecipe',
    request,
    metadata || {},
    this.methodDescriptorGetRecipe);
  }

  methodDescriptorListRecipes = new grpcWeb.MethodDescriptor(
    '/recipes.RecipeService/ListRecipes',
    grpcWeb.MethodType.UNARY,
    recipe_pb.ListRecipesRequest,
    recipe_pb.ListRecipesResponse,
    (request: recipe_pb.ListRecipesRequest) => {
      return request.serializeBinary();
    },
    recipe_pb.ListRecipesResponse.deserializeBinary
  );

  listRecipes(
    request: recipe_pb.ListRecipesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recipe_pb.ListRecipesResponse>;

  listRecipes(
    request: recipe_pb.ListRecipesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recipe_pb.ListRecipesResponse) => void): grpcWeb.ClientReadableStream<recipe_pb.ListRecipesResponse>;

  listRecipes(
    request: recipe_pb.ListRecipesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recipe_pb.ListRecipesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/recipes.RecipeService/ListRecipes',
        request,
        metadata || {},
        this.methodDescriptorListRecipes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/recipes.RecipeService/ListRecipes',
    request,
    metadata || {},
    this.methodDescriptorListRecipes);
  }

  methodDescriptorCreateRecipe = new grpcWeb.MethodDescriptor(
    '/recipes.RecipeService/CreateRecipe',
    grpcWeb.MethodType.UNARY,
    recipe_pb.CreateRecipeRequest,
    recipe_pb.CreateRecipeResponse,
    (request: recipe_pb.CreateRecipeRequest) => {
      return request.serializeBinary();
    },
    recipe_pb.CreateRecipeResponse.deserializeBinary
  );

  createRecipe(
    request: recipe_pb.CreateRecipeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recipe_pb.CreateRecipeResponse>;

  createRecipe(
    request: recipe_pb.CreateRecipeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recipe_pb.CreateRecipeResponse) => void): grpcWeb.ClientReadableStream<recipe_pb.CreateRecipeResponse>;

  createRecipe(
    request: recipe_pb.CreateRecipeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recipe_pb.CreateRecipeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/recipes.RecipeService/CreateRecipe',
        request,
        metadata || {},
        this.methodDescriptorCreateRecipe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/recipes.RecipeService/CreateRecipe',
    request,
    metadata || {},
    this.methodDescriptorCreateRecipe);
  }

  methodDescriptorUpdateRecipe = new grpcWeb.MethodDescriptor(
    '/recipes.RecipeService/UpdateRecipe',
    grpcWeb.MethodType.UNARY,
    recipe_pb.UpdateRecipeRequest,
    recipe_pb.UpdateRecipeResponse,
    (request: recipe_pb.UpdateRecipeRequest) => {
      return request.serializeBinary();
    },
    recipe_pb.UpdateRecipeResponse.deserializeBinary
  );

  updateRecipe(
    request: recipe_pb.UpdateRecipeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recipe_pb.UpdateRecipeResponse>;

  updateRecipe(
    request: recipe_pb.UpdateRecipeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recipe_pb.UpdateRecipeResponse) => void): grpcWeb.ClientReadableStream<recipe_pb.UpdateRecipeResponse>;

  updateRecipe(
    request: recipe_pb.UpdateRecipeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recipe_pb.UpdateRecipeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/recipes.RecipeService/UpdateRecipe',
        request,
        metadata || {},
        this.methodDescriptorUpdateRecipe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/recipes.RecipeService/UpdateRecipe',
    request,
    metadata || {},
    this.methodDescriptorUpdateRecipe);
  }

  methodDescriptorDeleteRecipe = new grpcWeb.MethodDescriptor(
    '/recipes.RecipeService/DeleteRecipe',
    grpcWeb.MethodType.UNARY,
    recipe_pb.DeleteRecipeRequest,
    recipe_pb.DeleteRecipeResponse,
    (request: recipe_pb.DeleteRecipeRequest) => {
      return request.serializeBinary();
    },
    recipe_pb.DeleteRecipeResponse.deserializeBinary
  );

  deleteRecipe(
    request: recipe_pb.DeleteRecipeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recipe_pb.DeleteRecipeResponse>;

  deleteRecipe(
    request: recipe_pb.DeleteRecipeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recipe_pb.DeleteRecipeResponse) => void): grpcWeb.ClientReadableStream<recipe_pb.DeleteRecipeResponse>;

  deleteRecipe(
    request: recipe_pb.DeleteRecipeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recipe_pb.DeleteRecipeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/recipes.RecipeService/DeleteRecipe',
        request,
        metadata || {},
        this.methodDescriptorDeleteRecipe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/recipes.RecipeService/DeleteRecipe',
    request,
    metadata || {},
    this.methodDescriptorDeleteRecipe);
  }

}

