// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/recipe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // 例: "200g", "1 tbsp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_proto_recipe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{0}
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingredient) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Recipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ingredients   []*Ingredient          `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps         []string               `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_proto_recipe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{1}
}

func (x *Recipe) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipe) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recipe) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipe) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Recipe) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Recipe) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Recipe) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeRequest) Reset() {
	*x = GetRecipeRequest{}
	mi := &file_proto_recipe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRequest) ProtoMessage() {}

func (x *GetRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeResponse) Reset() {
	*x = GetRecipeResponse{}
	mi := &file_proto_recipe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeResponse) ProtoMessage() {}

func (x *GetRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type ListRecipesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesRequest) Reset() {
	*x = ListRecipesRequest{}
	mi := &file_proto_recipe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesRequest) ProtoMessage() {}

func (x *ListRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesRequest.ProtoReflect.Descriptor instead.
func (*ListRecipesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{4}
}

func (x *ListRecipesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecipesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRecipesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*Recipe              `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesResponse) Reset() {
	*x = ListRecipesResponse{}
	mi := &file_proto_recipe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesResponse) ProtoMessage() {}

func (x *ListRecipesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesResponse.ProtoReflect.Descriptor instead.
func (*ListRecipesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{5}
}

func (x *ListRecipesResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *ListRecipesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	mi := &file_proto_recipe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRecipeRequest) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type CreateRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeResponse) Reset() {
	*x = CreateRecipeResponse{}
	mi := &file_proto_recipe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeResponse) ProtoMessage() {}

func (x *CreateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeResponse.ProtoReflect.Descriptor instead.
func (*CreateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type UpdateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecipeRequest) Reset() {
	*x = UpdateRecipeRequest{}
	mi := &file_proto_recipe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeRequest) ProtoMessage() {}

func (x *UpdateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRecipeRequest) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type UpdateRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecipeResponse) Reset() {
	*x = UpdateRecipeResponse{}
	mi := &file_proto_recipe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeResponse) ProtoMessage() {}

func (x *UpdateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type DeleteRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecipeRequest) Reset() {
	*x = DeleteRecipeRequest{}
	mi := &file_proto_recipe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeRequest) ProtoMessage() {}

func (x *DeleteRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecipeResponse) Reset() {
	*x = DeleteRecipeResponse{}
	mi := &file_proto_recipe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeResponse) ProtoMessage() {}

func (x *DeleteRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recipe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_recipe_proto_rawDescGZIP(), []int{11}
}

var File_proto_recipe_proto protoreflect.FileDescriptor

const file_proto_recipe_proto_rawDesc = "" +
	"\n" +
	"\x12proto/recipe.proto\x12\arecipes\"8\n" +
	"\n" +
	"Ingredient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xdb\x01\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\vingredients\x18\x04 \x03(\v2\x13.recipes.IngredientR\vingredients\x12\x14\n" +
	"\x05steps\x18\x05 \x03(\tR\x05steps\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\"\n" +
	"\x10GetRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x11GetRecipeResponse\x12'\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0f.recipes.RecipeR\x06recipe\"E\n" +
	"\x12ListRecipesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"V\n" +
	"\x13ListRecipesResponse\x12)\n" +
	"\arecipes\x18\x01 \x03(\v2\x0f.recipes.RecipeR\arecipes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\">\n" +
	"\x13CreateRecipeRequest\x12'\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0f.recipes.RecipeR\x06recipe\"?\n" +
	"\x14CreateRecipeResponse\x12'\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0f.recipes.RecipeR\x06recipe\">\n" +
	"\x13UpdateRecipeRequest\x12'\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0f.recipes.RecipeR\x06recipe\"?\n" +
	"\x14UpdateRecipeResponse\x12'\n" +
	"\x06recipe\x18\x01 \x01(\v2\x0f.recipes.RecipeR\x06recipe\"%\n" +
	"\x13DeleteRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteRecipeResponse2\x84\x03\n" +
	"\rRecipeService\x12B\n" +
	"\tGetRecipe\x12\x19.recipes.GetRecipeRequest\x1a\x1a.recipes.GetRecipeResponse\x12H\n" +
	"\vListRecipes\x12\x1b.recipes.ListRecipesRequest\x1a\x1c.recipes.ListRecipesResponse\x12K\n" +
	"\fCreateRecipe\x12\x1c.recipes.CreateRecipeRequest\x1a\x1d.recipes.CreateRecipeResponse\x12K\n" +
	"\fUpdateRecipe\x12\x1c.recipes.UpdateRecipeRequest\x1a\x1d.recipes.UpdateRecipeResponse\x12K\n" +
	"\fDeleteRecipe\x12\x1c.recipes.DeleteRecipeRequest\x1a\x1d.recipes.DeleteRecipeResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_recipe_proto_rawDescOnce sync.Once
	file_proto_recipe_proto_rawDescData []byte
)

func file_proto_recipe_proto_rawDescGZIP() []byte {
	file_proto_recipe_proto_rawDescOnce.Do(func() {
		file_proto_recipe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recipe_proto_rawDesc), len(file_proto_recipe_proto_rawDesc)))
	})
	return file_proto_recipe_proto_rawDescData
}

var file_proto_recipe_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_recipe_proto_goTypes = []any{
	(*Ingredient)(nil),           // 0: recipes.Ingredient
	(*Recipe)(nil),               // 1: recipes.Recipe
	(*GetRecipeRequest)(nil),     // 2: recipes.GetRecipeRequest
	(*GetRecipeResponse)(nil),    // 3: recipes.GetRecipeResponse
	(*ListRecipesRequest)(nil),   // 4: recipes.ListRecipesRequest
	(*ListRecipesResponse)(nil),  // 5: recipes.ListRecipesResponse
	(*CreateRecipeRequest)(nil),  // 6: recipes.CreateRecipeRequest
	(*CreateRecipeResponse)(nil), // 7: recipes.CreateRecipeResponse
	(*UpdateRecipeRequest)(nil),  // 8: recipes.UpdateRecipeRequest
	(*UpdateRecipeResponse)(nil), // 9: recipes.UpdateRecipeResponse
	(*DeleteRecipeRequest)(nil),  // 10: recipes.DeleteRecipeRequest
	(*DeleteRecipeResponse)(nil), // 11: recipes.DeleteRecipeResponse
}
var file_proto_recipe_proto_depIdxs = []int32{
	0,  // 0: recipes.Recipe.ingredients:type_name -> recipes.Ingredient
	1,  // 1: recipes.GetRecipeResponse.recipe:type_name -> recipes.Recipe
	1,  // 2: recipes.ListRecipesResponse.recipes:type_name -> recipes.Recipe
	1,  // 3: recipes.CreateRecipeRequest.recipe:type_name -> recipes.Recipe
	1,  // 4: recipes.CreateRecipeResponse.recipe:type_name -> recipes.Recipe
	1,  // 5: recipes.UpdateRecipeRequest.recipe:type_name -> recipes.Recipe
	1,  // 6: recipes.UpdateRecipeResponse.recipe:type_name -> recipes.Recipe
	2,  // 7: recipes.RecipeService.GetRecipe:input_type -> recipes.GetRecipeRequest
	4,  // 8: recipes.RecipeService.ListRecipes:input_type -> recipes.ListRecipesRequest
	6,  // 9: recipes.RecipeService.CreateRecipe:input_type -> recipes.CreateRecipeRequest
	8,  // 10: recipes.RecipeService.UpdateRecipe:input_type -> recipes.UpdateRecipeRequest
	10, // 11: recipes.RecipeService.DeleteRecipe:input_type -> recipes.DeleteRecipeRequest
	3,  // 12: recipes.RecipeService.GetRecipe:output_type -> recipes.GetRecipeResponse
	5,  // 13: recipes.RecipeService.ListRecipes:output_type -> recipes.ListRecipesResponse
	7,  // 14: recipes.RecipeService.CreateRecipe:output_type -> recipes.CreateRecipeResponse
	9,  // 15: recipes.RecipeService.UpdateRecipe:output_type -> recipes.UpdateRecipeResponse
	11, // 16: recipes.RecipeService.DeleteRecipe:output_type -> recipes.DeleteRecipeResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_recipe_proto_init() }
func file_proto_recipe_proto_init() {
	if File_proto_recipe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recipe_proto_rawDesc), len(file_proto_recipe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recipe_proto_goTypes,
		DependencyIndexes: file_proto_recipe_proto_depIdxs,
		MessageInfos:      file_proto_recipe_proto_msgTypes,
	}.Build()
	File_proto_recipe_proto = out.File
	file_proto_recipe_proto_goTypes = nil
	file_proto_recipe_proto_depIdxs = nil
}
